"""Добавил в таблицу Jobs колонку title

Revision ID: 03b5337729b1
Revises: 088b53f52f7b
Create Date: 2024-07-21 16:47:00.676259

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '03b5337729b1'
down_revision = '088b53f52f7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'jobs',
        sa.Column('title', sa.String(), nullable=True, comment='Название вакансии'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'title')
    # ### end Alembic commands ###
