"""Изменил таблицу Responce

Revision ID: 088b53f52f7b
Revises: 119556aae7cb
Create Date: 2024-07-21 14:57:35.306211

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "088b53f52f7b"
down_revision = "119556aae7cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "responses",
        sa.Column("massage", sa.String(), nullable=True, comment="Сопроводительное письмо"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("responses", "massage")
    # ### end Alembic commands ###
