"""Первоначальное создание таблиц

Revision ID: e31beef93767
Revises: 
Create Date: 2024-09-02 14:16:20.216650

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e31beef93767"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Идентификатор пользователя",
        ),
        sa.Column("email", sa.String(), nullable=False, comment="Email адрес"),
        sa.Column("name", sa.String(), nullable=False, comment="Имя пользователя"),
        sa.Column("hashed_password", sa.String(), nullable=False, comment="Зашифрованный пароль"),
        sa.Column("is_company", sa.Boolean(), nullable=False, comment="Флаг компании"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False, comment="Идентификатор вакансии"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="Идентификатор пользователя"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "responses",
        sa.Column("id", sa.Integer(), nullable=False, comment="Идентификатор отклика"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="Идентификатор пользователя"),
        sa.Column("job_id", sa.Integer(), nullable=False, comment="Идентификатор вакансии"),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("responses")
    op.drop_table("jobs")
    op.drop_table("users")
    # ### end Alembic commands ###
