"""Создание новых таблиц

Revision ID: 2e444e7e86e1
Revises: 
Create Date: 2024-07-30 14:10:36.445099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e444e7e86e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False, comment='Email адрес'),
    sa.Column('name', sa.String(), nullable=False, comment='Имя пользователя'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='Зашифрованный пароль'),
    sa.Column('is_company', sa.Boolean(), nullable=False, comment='Флаг компании'),
    sa.Column('id', sa.String(), nullable=False, comment='Идентификатор'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Время создания записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('title', sa.String(length=100), nullable=False, comment='Название вакансии'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание вакансии'),
    sa.Column('salary_from', sa.Float(), nullable=False, comment='Зарплата от'),
    sa.Column('salary_to', sa.Float(), nullable=False, comment='Зарплата до'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли вакансия '),
    sa.Column('user_id', sa.String(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('id', sa.String(), nullable=False, comment='Идентификатор'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Время создания записи'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('responses',
    sa.Column('message', sa.Text(), nullable=False, comment='Описание вакансии'),
    sa.Column('user_id', sa.String(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('job_id', sa.String(), nullable=False, comment='Идентификатор вакансии'),
    sa.Column('id', sa.String(), nullable=False, comment='Идентификатор'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Время создания записи'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
