"""cascade_rels

Revision ID: 3fa1a6c8ebf0
Revises: de82a9d0593d
Create Date: 2024-02-04 21:33:42.496418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa1a6c8ebf0'
down_revision = 'de82a9d0593d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jobs_user_id_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('responses_user_id_fkey', 'responses', type_='foreignkey')
    op.drop_constraint('responses_job_id_fkey', 'responses', type_='foreignkey')
    op.create_foreign_key(None, 'responses', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'responses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.create_foreign_key('responses_job_id_fkey', 'responses', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key('responses_user_id_fkey', 'responses', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_user_id_fkey', 'jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
