"""Добавлены поля в таблицу Job

Revision ID: 489d2b0de61a
Revises: cc7109d1bc74
Create Date: 2023-10-10 15:05:07.510749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489d2b0de61a'
down_revision = 'cc7109d1bc74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('title', sa.String(), nullable=False, comment='Название вакансии'))
    op.add_column('jobs', sa.Column('description', sa.String(), nullable=False, comment='Описание вакансии'))
    op.add_column('jobs', sa.Column('salary_from', sa.DECIMAL(), nullable=True, comment='Зарплата от'))
    op.add_column('jobs', sa.Column('salary_to', sa.DECIMAL(), nullable=True, comment='Зарплата до'))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли вакансия'))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=True, comment='Время создания записи'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'salary_to')
    op.drop_column('jobs', 'salary_from')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'title')
    # ### end Alembic commands ###
