"""Добавлена дата создания response

Revision ID: 5ea42135c5ca
Revises: 03b5337729b1
Create Date: 2024-07-23 12:15:13.437687

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5ea42135c5ca"
down_revision = "03b5337729b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "responses",
        sa.Column("created_at", sa.DateTime(), nullable=True, comment="Дата создания строки"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("responses", "created_at")
    # ### end Alembic commands ###
