"""скорректировал столбец response mEssage

Revision ID: 7b3fe8c00f8a
Revises: 5ea42135c5ca
Create Date: 2024-08-05 19:01:29.878634

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7b3fe8c00f8a"
down_revision = "5ea42135c5ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "responses",
        sa.Column("message", sa.String(), nullable=True, comment="Сопроводительное письмо"),
    )
    op.alter_column(
        "responses",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Дата создания записи",
        existing_comment="Дата создания строки",
        existing_nullable=True,
    )
    op.drop_column("responses", "massage")
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Дата создания записи",
        existing_comment="Дата создания строки",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Дата создания строки",
        existing_comment="Дата создания записи",
        existing_nullable=True,
    )
    op.add_column(
        "responses",
        sa.Column(
            "massage",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Сопроводительное письмо",
        ),
    )
    op.alter_column(
        "responses",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Дата создания строки",
        existing_comment="Дата создания записи",
        existing_nullable=True,
    )
    op.drop_column("responses", "message")
    # ### end Alembic commands ###
