"""Добавлены новые поля по схеме

Revision ID: 933cac93911b
Revises: e6b667630d8a
Create Date: 2024-04-17 12:05:44.473055

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "933cac93911b"
down_revision = "e6b667630d8a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column("title", sa.String(), nullable=True, comment="Название вакансии"),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "description", sa.String(), nullable=True, comment="Описание вакансии"
        ),
    )
    op.add_column(
        "jobs",
        sa.Column("salary_from", sa.Numeric(), nullable=True, comment="Зарплата от"),
    )
    op.add_column(
        "jobs",
        sa.Column("salary_to", sa.Numeric(), nullable=True, comment="Зарплата до"),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "is_active", sa.Boolean(), nullable=True, comment="Активна ли вакансия"
        ),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "created_at", sa.DateTime(), nullable=True, comment="Дата создания записи"
        ),
    )
    op.add_column(
        "responses",
        sa.Column(
            "message", sa.String(), nullable=True, comment="Сопроводительное письмо"
        ),
    )
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("responses", "message")
    op.drop_column("jobs", "created_at")
    op.drop_column("jobs", "is_active")
    op.drop_column("jobs", "salary_to")
    op.drop_column("jobs", "salary_from")
    op.drop_column("jobs", "description")
    op.drop_column("jobs", "title")
    # ### end Alembic commands ###
