"""Добавлено каскадное удаление вакансии

Revision ID: 982b1ad375ce
Revises: 933cac93911b
Create Date: 2024-04-17 16:47:09.350189

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "982b1ad375ce"
down_revision = "933cac93911b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
