"""привет, мир!

Revision ID: a93b5bb74272
Revises: 4cd6e4f04086
Create Date: 2024-06-25 17:11:53.768239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93b5bb74272'
down_revision = '4cd6e4f04086'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
