"""Fix salary

Revision ID: bec31fa3d676
Revises: ac4d6d99a669
Create Date: 2023-01-18 20:17:09.012089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec31fa3d676'
down_revision = 'ac4d6d99a669'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
