"""add column tables job and responses

Revision ID: c9fd30964ceb
Revises: e6b667630d8a
Create Date: 2023-05-26 09:35:43.456820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fd30964ceb'
down_revision = 'e6b667630d8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('title', sa.String(), nullable=True, comment='Название вакансии'))
    op.add_column('jobs', sa.Column('description', sa.String(), nullable=True, comment='Описание вакансии'))
    op.add_column('jobs', sa.Column('salary_from', sa.Numeric(), nullable=True, comment='Зарплата от'))
    op.add_column('jobs', sa.Column('salary_to', sa.Numeric(), nullable=True, comment='Зарплата до'))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=True, comment='Активна ли вакансия'))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=True, comment='Дата создания записи'))
    op.add_column('responses', sa.Column('message', sa.String(), nullable=True, comment='Сопроводительное письмо'))
    op.drop_constraint('responses_job_id_fkey', 'responses', type_='foreignkey')
    op.drop_constraint('responses_user_id_fkey', 'responses', type_='foreignkey')
    op.create_foreign_key(None, 'responses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'responses', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.create_foreign_key('responses_user_id_fkey', 'responses', 'users', ['user_id'], ['id'])
    op.create_foreign_key('responses_job_id_fkey', 'responses', 'jobs', ['job_id'], ['id'])
    op.drop_column('responses', 'message')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'salary_to')
    op.drop_column('jobs', 'salary_from')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'title')
    # ### end Alembic commands ###
