"""Добавлено поле message в таблице responses

Revision ID: cc7109d1bc74
Revises: e6b667630d8a
Create Date: 2023-10-10 14:41:24.813650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7109d1bc74'
down_revision = 'e6b667630d8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('message', sa.String(), nullable=True, comment='Сопроводительное письмо'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'message')
    # ### end Alembic commands ###
