"""Добавлены доп поля в таблицы jobs и responses

Revision ID: d44963082fe1
Revises: e6b667630d8a
Create Date: 2024-07-29 18:38:34.913429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd44963082fe1'
down_revision = 'e6b667630d8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('title', sa.String(length=100), nullable=False, comment='Название вакансии'))
    op.add_column('jobs', sa.Column('description', sa.Text(), nullable=False, comment='Описание вакансии'))
    op.add_column('jobs', sa.Column('salary_from', sa.Float(), nullable=False, comment='Зарплата от'))
    op.add_column('jobs', sa.Column('salary_to', sa.Float(), nullable=False, comment='Зарплата до'))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли вакансия '))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=False, comment='Время создания записи'))
    op.alter_column('jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор пользователя')
    op.alter_column('jobs', 'id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор',
               existing_comment='Идентификатор вакансии',
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'jobs', ['id'])
    op.add_column('responses', sa.Column('message', sa.Text(), nullable=False, comment='Описание вакансии'))
    op.add_column('responses', sa.Column('created_at', sa.DateTime(), nullable=False, comment='Время создания записи'))
    op.alter_column('responses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор пользователя')
    op.alter_column('responses', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор вакансии')
    op.alter_column('responses', 'id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор',
               existing_comment='Идентификатор отклика',
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'responses', ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Email адрес')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Имя пользователя')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               nullable=False,
               existing_comment='Зашифрованный пароль')
    op.alter_column('users', 'is_company',
               existing_type=sa.BOOLEAN(),
               type_=sa.LargeBinary(),
               nullable=False,
               existing_comment='Флаг компании')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор',
               existing_comment='Идентификатор задачи',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Время создания записи')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Время создания записи')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор задачи',
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('users', 'is_company',
               existing_type=sa.LargeBinary(),
               type_=sa.BOOLEAN(),
               nullable=True,
               existing_comment='Флаг компании')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_comment='Зашифрованный пароль')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Имя пользователя')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Email адрес')
    op.drop_constraint(None, 'responses', type_='unique')
    op.alter_column('responses', 'id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор отклика',
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('responses', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор вакансии')
    op.alter_column('responses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор пользователя')
    op.drop_column('responses', 'created_at')
    op.drop_column('responses', 'message')
    op.drop_constraint(None, 'jobs', type_='unique')
    op.alter_column('jobs', 'id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор вакансии',
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор пользователя')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'salary_to')
    op.drop_column('jobs', 'salary_from')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'title')
    # ### end Alembic commands ###
