"""Create tables

Revision ID: 272a94fcabff
Revises:
Create Date: 2024-01-22 16:21:01.402535

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "272a94fcabff"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="Идентификатор пользователя"),
        sa.Column("email", sa.String(length=255), nullable=False, comment="Email адрес"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Имя пользователя"),
        sa.Column("hashed_password", sa.String(), nullable=False, comment="Хэш пароля"),
        sa.Column(
            "is_company",
            sa.Boolean(),
            server_default="f",
            nullable=False,
            comment="Признак, является ли юзер компанией",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
            comment="Время создания записи",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="Идентификатор вакансии"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="Идентификатор пользователя"),
        sa.Column("title", sa.String(length=255), nullable=False, comment="Название вакансии"),
        sa.Column("description", sa.String(), nullable=False, comment="Описание вакансии"),
        sa.Column("salary_from", sa.NUMERIC(scale=2), nullable=True, comment="Нижний порог зарплаты"),
        sa.Column("salary_to", sa.NUMERIC(scale=2), nullable=True, comment="Верхний порог запрлаты"),
        sa.Column(
            "is_active", sa.Boolean(), server_default="t", nullable=False, comment="Признак, активна ли вакансия"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=True,
            comment="Время создания записи",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "responses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="Идентификатор отклика"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="Идентификатор пользователя"),
        sa.Column("job_id", sa.Integer(), nullable=False, comment="Идентификатор вакансии"),
        sa.Column("message", sa.String(length=500), nullable=True, comment="Сопроводительное письмо"),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("responses")
    op.drop_table("jobs")
    op.drop_table("users")
    # ### end Alembic commands ###
