name: Test Python App

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Postgres
      working-directory: ./
      run: docker-compose -f docker-compose.yaml up -d

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/src/requirements.txt
    - name: Run migrations
      working-directory: ./backend/src/
      run: |
        alembic upgrade head
      env:
        PG_USER: admin
        PG_PASS: admin
        PG_DB: labor_exchange

    - name: Test with pytest
      working-directory: ./backend/src
      run: |
        pytest
